apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
spec:  # Spécifie la configuration souhaitée pour le déploiement.
  replicas: 1  # Vous pouvez ajuster ce nombre selon vos besoins
  selector: #Définit comment sélectionner les pods gérés par ce déploiement.
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: springboot-docker-container
          image: projet-angular:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-serv:3306/docker-db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-username
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: password
